---
title: "Circular Economy Course"
description: |

author:
  - first_name: "Fabio"
    last_name: "Cruz"
    url: https://erpi.univ-lorraine.fr/people/Fabio-Cruz/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0001-8529-5327
  - first_name: "Fedoua"
    last_name: "Kasmi"
    url: https://erpi.univ-lorraine.fr/people/Fedoua-Kasmi/
    affiliation: ERPI
    affiliation_url: https://erpi.univ-lorraine.fr/
    orcid_id: 0000-0001-5159-0264
bibliography: library.bib
csl: journal-of-cleaner-production.csl
link-citations: yes
linkcolor: blue 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

require(tidyverse)
require(xaringan)
require(xaringanExtra)
# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Objectives
- Implement the consumer-driven DIT process within the four use cases 
- Validate the INEDIT process specifications 
- Experiment and validate the result 
- Identify potential gender issues and insights to overcome them



# Presentation


```{r embed-xaringan, echo=FALSE}

embed_xaringan(url = "slides/index.html", ratio = "16:9")

```

